//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRouterPolicy) DeepCopyInto(out *ClusterRouterPolicy) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRouterPolicy.
func (in *ClusterRouterPolicy) DeepCopy() *ClusterRouterPolicy {
	if in == nil {
		return nil
	}
	out := new(ClusterRouterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayChassis) DeepCopyInto(out *GatewayChassis) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayChassis.
func (in *GatewayChassis) DeepCopy() *GatewayChassis {
	if in == nil {
		return nil
	}
	out := new(GatewayChassis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L3Gateway) DeepCopyInto(out *L3Gateway) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L3Gateway.
func (in *L3Gateway) DeepCopy() *L3Gateway {
	if in == nil {
		return nil
	}
	out := new(L3Gateway)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NATRule) DeepCopyInto(out *NATRule) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NATRule.
func (in *NATRule) DeepCopy() *NATRule {
	if in == nil {
		return nil
	}
	out := new(NATRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Peer) DeepCopyInto(out *Peer) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Peer.
func (in *Peer) DeepCopy() *Peer {
	if in == nil {
		return nil
	}
	out := new(Peer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCNetwork) DeepCopyInto(out *VPCNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCNetwork.
func (in *VPCNetwork) DeepCopy() *VPCNetwork {
	if in == nil {
		return nil
	}
	out := new(VPCNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCNetworkList) DeepCopyInto(out *VPCNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCNetworkList.
func (in *VPCNetworkList) DeepCopy() *VPCNetworkList {
	if in == nil {
		return nil
	}
	out := new(VPCNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCNetworkSpec) DeepCopyInto(out *VPCNetworkSpec) {
	*out = *in
	if in.GatewayChassis != nil {
		in, out := &in.GatewayChassis, &out.GatewayChassis
		*out = make([]GatewayChassis, len(*in))
		copy(*out, *in)
	}
	if in.L3Gateways != nil {
		in, out := &in.L3Gateways, &out.L3Gateways
		*out = make([]L3Gateway, len(*in))
		copy(*out, *in)
	}
	if in.Peers != nil {
		in, out := &in.Peers, &out.Peers
		*out = make([]Peer, len(*in))
		copy(*out, *in)
	}
	if in.ClusterRouterPolicies != nil {
		in, out := &in.ClusterRouterPolicies, &out.ClusterRouterPolicies
		*out = make([]ClusterRouterPolicy, len(*in))
		copy(*out, *in)
	}
	if in.Nats != nil {
		in, out := &in.Nats, &out.Nats
		*out = make([]NATRule, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCNetworkSpec.
func (in *VPCNetworkSpec) DeepCopy() *VPCNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(VPCNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCNetworkStatus) DeepCopyInto(out *VPCNetworkStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCNetworkStatus.
func (in *VPCNetworkStatus) DeepCopy() *VPCNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(VPCNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnet) DeepCopyInto(out *VPCSubnet) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnet.
func (in *VPCSubnet) DeepCopy() *VPCSubnet {
	if in == nil {
		return nil
	}
	out := new(VPCSubnet)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCSubnet) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnetList) DeepCopyInto(out *VPCSubnetList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VPCSubnet, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnetList.
func (in *VPCSubnetList) DeepCopy() *VPCSubnetList {
	if in == nil {
		return nil
	}
	out := new(VPCSubnetList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VPCSubnetList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VPCSubnetSpec) DeepCopyInto(out *VPCSubnetSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VPCSubnetSpec.
func (in *VPCSubnetSpec) DeepCopy() *VPCSubnetSpec {
	if in == nil {
		return nil
	}
	out := new(VPCSubnetSpec)
	in.DeepCopyInto(out)
	return out
}
