/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	"context"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1 "kubesphere.io/api/vpc/v1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// VPCSubnetsGetter has a method to return a VPCSubnetInterface.
// A group's client should implement this interface.
type VPCSubnetsGetter interface {
	VPCSubnets(namespace string) VPCSubnetInterface
}

// VPCSubnetInterface has methods to work with VPCSubnet resources.
type VPCSubnetInterface interface {
	Create(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.CreateOptions) (*v1.VPCSubnet, error)
	Update(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.UpdateOptions) (*v1.VPCSubnet, error)
	UpdateStatus(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.UpdateOptions) (*v1.VPCSubnet, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.VPCSubnet, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.VPCSubnetList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VPCSubnet, err error)
	VPCSubnetExpansion
}

// vPCSubnets implements VPCSubnetInterface
type vPCSubnets struct {
	client rest.Interface
	ns     string
}

// newVPCSubnets returns a VPCSubnets
func newVPCSubnets(c *K8sV1Client, namespace string) *vPCSubnets {
	return &vPCSubnets{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the vPCSubnet, and returns the corresponding vPCSubnet object, and an error if there is any.
func (c *vPCSubnets) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.VPCSubnet, err error) {
	result = &v1.VPCSubnet{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vpcsubnets").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of VPCSubnets that match those selectors.
func (c *vPCSubnets) List(ctx context.Context, opts metav1.ListOptions) (result *v1.VPCSubnetList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.VPCSubnetList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("vpcsubnets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested vPCSubnets.
func (c *vPCSubnets) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("vpcsubnets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a vPCSubnet and creates it.  Returns the server's representation of the vPCSubnet, and an error, if there is any.
func (c *vPCSubnets) Create(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.CreateOptions) (result *v1.VPCSubnet, err error) {
	result = &v1.VPCSubnet{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("vpcsubnets").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPCSubnet).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a vPCSubnet and updates it. Returns the server's representation of the vPCSubnet, and an error, if there is any.
func (c *vPCSubnets) Update(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.UpdateOptions) (result *v1.VPCSubnet, err error) {
	result = &v1.VPCSubnet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vpcsubnets").
		Name(vPCSubnet.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPCSubnet).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *vPCSubnets) UpdateStatus(ctx context.Context, vPCSubnet *v1.VPCSubnet, opts metav1.UpdateOptions) (result *v1.VPCSubnet, err error) {
	result = &v1.VPCSubnet{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("vpcsubnets").
		Name(vPCSubnet.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(vPCSubnet).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the vPCSubnet and deletes it. Returns an error if one occurs.
func (c *vPCSubnets) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vpcsubnets").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *vPCSubnets) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("vpcsubnets").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched vPCSubnet.
func (c *vPCSubnets) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.VPCSubnet, err error) {
	result = &v1.VPCSubnet{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("vpcsubnets").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
