/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/even/v1alpha1"
)

// FakeEvens implements EvenInterface
type FakeEvens struct {
	Fake *FakeEvenV1alpha1
	ns   string
}

var evensResource = schema.GroupVersionResource{Group: "even.ecpaas.io", Version: "v1alpha1", Resource: "evens"}

var evensKind = schema.GroupVersionKind{Group: "even.ecpaas.io", Version: "v1alpha1", Kind: "Even"}

// Get takes name of the even, and returns the corresponding even object, and an error if there is any.
func (c *FakeEvens) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Even, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(evensResource, c.ns, name), &v1alpha1.Even{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Even), err
}

// List takes label and field selectors, and returns the list of Evens that match those selectors.
func (c *FakeEvens) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.EvenList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(evensResource, evensKind, c.ns, opts), &v1alpha1.EvenList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.EvenList{ListMeta: obj.(*v1alpha1.EvenList).ListMeta}
	for _, item := range obj.(*v1alpha1.EvenList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested evens.
func (c *FakeEvens) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(evensResource, c.ns, opts))

}

// Create takes the representation of a even and creates it.  Returns the server's representation of the even, and an error, if there is any.
func (c *FakeEvens) Create(ctx context.Context, even *v1alpha1.Even, opts v1.CreateOptions) (result *v1alpha1.Even, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(evensResource, c.ns, even), &v1alpha1.Even{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Even), err
}

// Update takes the representation of a even and updates it. Returns the server's representation of the even, and an error, if there is any.
func (c *FakeEvens) Update(ctx context.Context, even *v1alpha1.Even, opts v1.UpdateOptions) (result *v1alpha1.Even, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(evensResource, c.ns, even), &v1alpha1.Even{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Even), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeEvens) UpdateStatus(ctx context.Context, even *v1alpha1.Even, opts v1.UpdateOptions) (*v1alpha1.Even, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(evensResource, "status", c.ns, even), &v1alpha1.Even{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Even), err
}

// Delete takes name of the even and deletes it. Returns an error if one occurs.
func (c *FakeEvens) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(evensResource, c.ns, name), &v1alpha1.Even{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeEvens) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(evensResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.EvenList{})
	return err
}

// Patch applies the patch and returns the patched even.
func (c *FakeEvens) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Even, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(evensResource, c.ns, name, pt, data, subresources...), &v1alpha1.Even{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Even), err
}
