/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// DataVolumeBlankImagesGetter has a method to return a DataVolumeBlankImageInterface.
// A group's client should implement this interface.
type DataVolumeBlankImagesGetter interface {
	DataVolumeBlankImages() DataVolumeBlankImageInterface
}

// DataVolumeBlankImageInterface has methods to work with DataVolumeBlankImage resources.
type DataVolumeBlankImageInterface interface {
	Create(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.CreateOptions) (*v1alpha1.DataVolumeBlankImage, error)
	Update(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.UpdateOptions) (*v1alpha1.DataVolumeBlankImage, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DataVolumeBlankImage, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DataVolumeBlankImageList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataVolumeBlankImage, err error)
	DataVolumeBlankImageExpansion
}

// dataVolumeBlankImages implements DataVolumeBlankImageInterface
type dataVolumeBlankImages struct {
	client rest.Interface
}

// newDataVolumeBlankImages returns a DataVolumeBlankImages
func newDataVolumeBlankImages(c *VirtualizationV1alpha1Client) *dataVolumeBlankImages {
	return &dataVolumeBlankImages{
		client: c.RESTClient(),
	}
}

// Get takes name of the dataVolumeBlankImage, and returns the corresponding dataVolumeBlankImage object, and an error if there is any.
func (c *dataVolumeBlankImages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	result = &v1alpha1.DataVolumeBlankImage{}
	err = c.client.Get().
		Resource("datavolumeblankimages").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DataVolumeBlankImages that match those selectors.
func (c *dataVolumeBlankImages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataVolumeBlankImageList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DataVolumeBlankImageList{}
	err = c.client.Get().
		Resource("datavolumeblankimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested dataVolumeBlankImages.
func (c *dataVolumeBlankImages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Resource("datavolumeblankimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a dataVolumeBlankImage and creates it.  Returns the server's representation of the dataVolumeBlankImage, and an error, if there is any.
func (c *dataVolumeBlankImages) Create(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.CreateOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	result = &v1alpha1.DataVolumeBlankImage{}
	err = c.client.Post().
		Resource("datavolumeblankimages").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataVolumeBlankImage).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a dataVolumeBlankImage and updates it. Returns the server's representation of the dataVolumeBlankImage, and an error, if there is any.
func (c *dataVolumeBlankImages) Update(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.UpdateOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	result = &v1alpha1.DataVolumeBlankImage{}
	err = c.client.Put().
		Resource("datavolumeblankimages").
		Name(dataVolumeBlankImage.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(dataVolumeBlankImage).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the dataVolumeBlankImage and deletes it. Returns an error if one occurs.
func (c *dataVolumeBlankImages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("datavolumeblankimages").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *dataVolumeBlankImages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Resource("datavolumeblankimages").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched dataVolumeBlankImage.
func (c *dataVolumeBlankImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataVolumeBlankImage, err error) {
	result = &v1alpha1.DataVolumeBlankImage{}
	err = c.client.Patch(pt).
		Resource("datavolumeblankimages").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
