/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
	scheme "kubesphere.io/kubesphere/pkg/client/clientset/versioned/scheme"
)

// ImageTemplatesGetter has a method to return a ImageTemplateInterface.
// A group's client should implement this interface.
type ImageTemplatesGetter interface {
	ImageTemplates(namespace string) ImageTemplateInterface
}

// ImageTemplateInterface has methods to work with ImageTemplate resources.
type ImageTemplateInterface interface {
	Create(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.CreateOptions) (*v1alpha1.ImageTemplate, error)
	Update(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.UpdateOptions) (*v1alpha1.ImageTemplate, error)
	UpdateStatus(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.UpdateOptions) (*v1alpha1.ImageTemplate, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ImageTemplate, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ImageTemplateList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageTemplate, err error)
	ImageTemplateExpansion
}

// imageTemplates implements ImageTemplateInterface
type imageTemplates struct {
	client rest.Interface
	ns     string
}

// newImageTemplates returns a ImageTemplates
func newImageTemplates(c *VirtualizationV1alpha1Client, namespace string) *imageTemplates {
	return &imageTemplates{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageTemplate, and returns the corresponding imageTemplate object, and an error if there is any.
func (c *imageTemplates) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageTemplate, err error) {
	result = &v1alpha1.ImageTemplate{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagetemplates").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageTemplates that match those selectors.
func (c *imageTemplates) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageTemplateList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ImageTemplateList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagetemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageTemplates.
func (c *imageTemplates) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagetemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a imageTemplate and creates it.  Returns the server's representation of the imageTemplate, and an error, if there is any.
func (c *imageTemplates) Create(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.CreateOptions) (result *v1alpha1.ImageTemplate, err error) {
	result = &v1alpha1.ImageTemplate{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagetemplates").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageTemplate).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a imageTemplate and updates it. Returns the server's representation of the imageTemplate, and an error, if there is any.
func (c *imageTemplates) Update(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.UpdateOptions) (result *v1alpha1.ImageTemplate, err error) {
	result = &v1alpha1.ImageTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagetemplates").
		Name(imageTemplate.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageTemplate).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *imageTemplates) UpdateStatus(ctx context.Context, imageTemplate *v1alpha1.ImageTemplate, opts v1.UpdateOptions) (result *v1alpha1.ImageTemplate, err error) {
	result = &v1alpha1.ImageTemplate{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagetemplates").
		Name(imageTemplate.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageTemplate).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the imageTemplate and deletes it. Returns an error if one occurs.
func (c *imageTemplates) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagetemplates").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageTemplates) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagetemplates").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched imageTemplate.
func (c *imageTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageTemplate, err error) {
	result = &v1alpha1.ImageTemplate{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagetemplates").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
