/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
)

// DataVolumeBlankImageLister helps list DataVolumeBlankImages.
// All objects returned here must be treated as read-only.
type DataVolumeBlankImageLister interface {
	// List lists all DataVolumeBlankImages in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.DataVolumeBlankImage, err error)
	// Get retrieves the DataVolumeBlankImage from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.DataVolumeBlankImage, error)
	DataVolumeBlankImageListerExpansion
}

// dataVolumeBlankImageLister implements the DataVolumeBlankImageLister interface.
type dataVolumeBlankImageLister struct {
	indexer cache.Indexer
}

// NewDataVolumeBlankImageLister returns a new DataVolumeBlankImageLister.
func NewDataVolumeBlankImageLister(indexer cache.Indexer) DataVolumeBlankImageLister {
	return &dataVolumeBlankImageLister{indexer: indexer}
}

// List lists all DataVolumeBlankImages in the indexer.
func (s *dataVolumeBlankImageLister) List(selector labels.Selector) (ret []*v1alpha1.DataVolumeBlankImage, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.DataVolumeBlankImage))
	})
	return ret, err
}

// Get retrieves the DataVolumeBlankImage from the index for a given name.
func (s *dataVolumeBlankImageLister) Get(name string) (*v1alpha1.DataVolumeBlankImage, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("datavolumeblankimage"), name)
	}
	return obj.(*v1alpha1.DataVolumeBlankImage), nil
}
