/*
Copyright 2020 The KubeSphere Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
	v1alpha1 "kubesphere.io/api/virtualization/v1alpha1"
)

// FakeDataVolumeBlankImages implements DataVolumeBlankImageInterface
type FakeDataVolumeBlankImages struct {
	Fake *FakeVirtualizationV1alpha1
}

var datavolumeblankimagesResource = schema.GroupVersionResource{Group: "virtualization.ecpaas.io", Version: "v1alpha1", Resource: "datavolumeblankimages"}

var datavolumeblankimagesKind = schema.GroupVersionKind{Group: "virtualization.ecpaas.io", Version: "v1alpha1", Kind: "DataVolumeBlankImage"}

// Get takes name of the dataVolumeBlankImage, and returns the corresponding dataVolumeBlankImage object, and an error if there is any.
func (c *FakeDataVolumeBlankImages) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(datavolumeblankimagesResource, name), &v1alpha1.DataVolumeBlankImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataVolumeBlankImage), err
}

// List takes label and field selectors, and returns the list of DataVolumeBlankImages that match those selectors.
func (c *FakeDataVolumeBlankImages) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DataVolumeBlankImageList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(datavolumeblankimagesResource, datavolumeblankimagesKind, opts), &v1alpha1.DataVolumeBlankImageList{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataVolumeBlankImageList), err
}

// Watch returns a watch.Interface that watches the requested dataVolumeBlankImages.
func (c *FakeDataVolumeBlankImages) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(datavolumeblankimagesResource, opts))
}

// Create takes the representation of a dataVolumeBlankImage and creates it.  Returns the server's representation of the dataVolumeBlankImage, and an error, if there is any.
func (c *FakeDataVolumeBlankImages) Create(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.CreateOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(datavolumeblankimagesResource, dataVolumeBlankImage), &v1alpha1.DataVolumeBlankImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataVolumeBlankImage), err
}

// Update takes the representation of a dataVolumeBlankImage and updates it. Returns the server's representation of the dataVolumeBlankImage, and an error, if there is any.
func (c *FakeDataVolumeBlankImages) Update(ctx context.Context, dataVolumeBlankImage *v1alpha1.DataVolumeBlankImage, opts v1.UpdateOptions) (result *v1alpha1.DataVolumeBlankImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(datavolumeblankimagesResource, dataVolumeBlankImage), &v1alpha1.DataVolumeBlankImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataVolumeBlankImage), err
}

// Delete takes name of the dataVolumeBlankImage and deletes it. Returns an error if one occurs.
func (c *FakeDataVolumeBlankImages) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(datavolumeblankimagesResource, name), &v1alpha1.DataVolumeBlankImage{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDataVolumeBlankImages) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(datavolumeblankimagesResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DataVolumeBlankImageList{})
	return err
}

// Patch applies the patch and returns the patched dataVolumeBlankImage.
func (c *FakeDataVolumeBlankImages) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DataVolumeBlankImage, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(datavolumeblankimagesResource, name, pt, data, subresources...), &v1alpha1.DataVolumeBlankImage{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DataVolumeBlankImage), err
}
